siges/Models/Operador.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;

namespace siges.Models {
    public class Operador {
        public int Id {get; set;}
        public bool Estatus {get; set;}
        public OrdenServicio OrdenServicio {get; set;}
        public Persona Persona {get; set;}
        public DateTime Hora {get; set;}
        public List<Operador.Estado> EstadoN {get; set;}
        public DateTime FechaAdministrativa {get; set;}

        public Operador(){
            this.EstadoN = new List<Operador.Estado>();
            this.Hora = new DateTime();
            this.FechaAdministrativa = new DateTime();
        }
        public class Estado{
            public int Id {get; set;}
            public string NuevoEstado {get; set;}
            public string ComentarioNuevoEstado {get; set;}
            public List<Operador.Estado.Archivo> ArchivosEvidencia {get; set;}

            public Estado(){
              ArchivosEvidencia = new List<Operador.Estado.Archivo>();
            }
            public class Archivo{
                public int Id {get; set;}
                public string Path {get; set;}
                public string Type {get; set;}
                public string Name {get; set;}
                public string Exif {get; set;}
                public string ExifBi {get; set;}
                public long Size {get; set;}
                public byte[] File {get; set;}
                public DateTime LastModified {get; set;}
                public EstructuraExifBi EstructuraExif {get; set;}
                public string FaceApiFinalResponse {get; set;}
                public string CustomVisionResult {get;set;}
                public List<EstructuraCustomVision> EstructuraCustomVisionResult {get;set;}

                public Archivo(){
                  EstructuraExif = new EstructuraExifBi();
                  EstructuraCustomVisionResult = new List<EstructuraCustomVision>();
                }
            }
        }
    }
}

siges/Controllers/OperadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Data;
using System.IO;
using System.Globalization;

using siges.Models;
using siges.DTO;
using siges.Repository;
using siges.Utilities;
using siges.Areas.Identity.Data;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

using MimeKit;

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

using RestSharp;

namespace siges.Controllers {
  [Authorize(Roles = "Operador, SuperUser")]
  public class OperadorController : Controller {
    private readonly IHostingEnvironment _hostingEnvironment;
    private List<Persona> _listOperador;
    private readonly UserManager<RoatechIdentityUser> _userManager;
    private readonly RoleManager<IdentityRole> _roleManager;
    private readonly IEmailConfiguration _emailConf;
    private IPersonaRepository _pRepo;
    private IOrdenPersona _opRepo;
    private IOperador _operRepo;
    private IOrdenServicioRepository _osRepo;
    private Persona operadorP;
    private Operador operadorActual;
    private List<string> EstadosOperador;
    private int opId;
    private Settings settings;
    private readonly IRoatechIdentityUserRepo roaIdenUsrRepo;

    public OperadorController(UserManager<RoatechIdentityUser> userManager, RoleManager<IdentityRole> roleManager, IOrdenPersona opRepo, IOrdenServicioRepository osRepo, IPersonaRepository pRepo, IOperador operRepo, IHostingEnvironment hEnv, IEmailConfiguration emailConf, ISettingsRepository set, IRoatechIdentityUserRepo _riuR) {
      _pRepo = pRepo;
      _opRepo = opRepo;
      _userManager = userManager;
      _roleManager = roleManager;
      _operRepo = operRepo;
      _osRepo = osRepo;
      _hostingEnvironment = hEnv;
      _emailConf = emailConf;
      operadorActual = new Operador();
      settings = set.GetByVersion("DAMSA");
      roaIdenUsrRepo = _riuR;
    }

    public async Task<IActionResult> Index() {
      var usr = await _userManager.GetUserAsync(HttpContext.User);
      Console.WriteLine("\n\nuser: "+ usr + "\n");
      opId = _pRepo.GetByEmail((await _userManager.GetUserAsync(HttpContext.User)).ToString()).Single().Id;
      var op =  _opRepo.GetOSbyIdP(opId).ToList();
      List<OrdenPersona> ordPer = new List<OrdenPersona>();
      foreach (var ordenPerso in op) {
        if(ordenPerso.OrdenServicio.Estatus)
          if(ordenPerso.OrdenServicio.FechaInicio != null && ordenPerso.OrdenServicio.FechaFin != null)
            if(ordenPerso.OrdenServicio.EstatusServicio == "programado" || ordenPerso.OrdenServicio.EstatusServicio == "reprogramado" || ordenPerso.OrdenServicio.EstatusServicio == "solicitado") {
              ordPer.Add(ordenPerso);
            }
      }
      foreach(OrdenPersona ordenpersona in ordPer){
        Console.WriteLine("\n\n\t"+ordenpersona.OrdenServicio.Folio+" "+ordenpersona.OrdenServicio.EstatusServicio+" "+ordenpersona.Persona.Nombre+ordenpersona.Persona.Paterno+"\n");
      }
      JsonSerializerSettings jsonSettings = new JsonSerializerSettings();
      jsonSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
      jsonSettings.NullValueHandling = NullValueHandling.Ignore;
      string output = JsonConvert.SerializeObject(ordPer, jsonSettings);
      ViewData["ordenesOperador"] = output;
      ViewData["ordenesPersona"] = ordPer;
      ViewData["OrdenServicioEnTiempo"] = JsonConvert.SerializeObject(getOSenTiempoOperador().Result, jsonSettings);
      RoatechIdentityUser riu = roaIdenUsrRepo.GetAllInfoByEmail(User.Identity.Name).Single();
      ViewData["riu"] = riu;
      return View();
    }

    [HttpPost]
    public IActionResult ReporteActividad(OperadorDTO operador){
      Console.WriteLine("\n\nOperadorDTO {0} {1} {2} {3} {4} {5}\n\n", operador.OrdenServicioId, operador.PersonaId, operador.NuevoEstado, operador.ComentarioNuevoEstado, operador.Hora, operador.ArchivosEvidencia);
      List<Operador> osAtendido = _operRepo.GetAtencionServicio(operador.OrdenServicioId).ToList();
      ViewData["osAtendido"] = osAtendido;
      return View();
    }

    private async Task<int> getOperadorId(){
      return _pRepo.GetByEmail((await _userManager.GetUserAsync(HttpContext.User)).ToString()).Single().Id;
      //return _pRepo.GetByEmail("juan@correo.com").Single().Id;
    }

    private async Task<List<OrdenPersona>> getOSenTiempoOperador(){
      List<OrdenPersona> ordSerOper = new List<OrdenPersona>();
      Console.WriteLine(" _opRepo.GetOSbyIdP(getOperadorId().Result).ToList(): "+ _opRepo.GetOSbyIdP(getOperadorId().Result).ToList().Count+"\n");
      foreach(var ordenPersona in _opRepo.GetOSbyIdP(getOperadorId().Result).ToList()){
        if(ordenPersona.OrdenServicio.Estatus){
          if(ordenPersona.OrdenServicio.FechaInicio != null && ordenPersona.OrdenServicio.FechaFin != null){
            if(ordenPersona.OrdenServicio.EstatusServicio == "programado" || ordenPersona.OrdenServicio.EstatusServicio == "reprogramado" || ordenPersona.OrdenServicio.EstatusServicio == "solicitado"){

                  //ordSerOper.Add(ordenPersona);// deja pasar todas las fechas disponibles

              switch(DateTime.Compare(DateTime.Now, (DateTime)ordenPersona.OrdenServicio.FechaInicio)){
                case -1: //Hoy es antes de FechaInicio
                  ViewData["estados"] = "destiempo";
                  break;
                case 0: //Hoy es el mismo de FechaInicio
                  ordSerOper.Add(ordenPersona);
                  ViewData["estados"] = "entiempo";
                  break;
                case 1: //Hoy es después de FechaInicio
                  switch(DateTime.Compare(DateTime.Now, ((DateTime)ordenPersona.OrdenServicio.FechaFin).AddDays(15))){
                    case -1: //Hoy es antes de FechaFin
                      ordSerOper.Add(ordenPersona);
                      ViewData["estados"] = "entiempo";
                      break;
                    case 0: //Hoy es el mismo de FechaFin
                      ordSerOper.Add(ordenPersona);
                      ViewData["estados"] = "entiempo";
                      break;
                    case 1: //Hoy es después de FechaFin
                      ViewData["estados"] = "destiempo";
                      break;
                  }
                  break;
              }
            }
          }
        }
      }
      return ordSerOper;
    }

    [HttpPost]
    public IActionResult CambiarEstado(OperadorDTO operador) {
      Console.WriteLine("-------------");
      Console.WriteLine(operador.OrdenServicioId);
      Console.WriteLine("-------------");
      
      foreach (var ordenServicio in _osRepo.GetAll(true).OrderBy(r => r.FechaInicio).ToList()) {
        if (ordenServicio.Id == operador.OrdenServicioId) {
          ViewData["ordenServicio"] = ordenServicio;
        }
      }
      List<Operador> listOperador = _operRepo.GetAtencionServicio(operador.OrdenServicioId).ToList();
      if(listOperador.Count == 0){
        ViewData["estados"] = "todos";
      } else {
        foreach(Operador oper in listOperador) {
          foreach(Operador.Estado esta in oper.EstadoN){
            switch(DateTime.Compare(DateTime.Today, oper.Hora.Date)){
              case -1: //Hoy es antes que evidencia
                ViewData["estados"] = "vacio";
                ViewData["diff"] = DateTime.Today.Subtract(oper.Hora.Date);
                break;
              case 0: //Hoy es mismo que evidencia
                if(settings.FaceApiUso){
                  if(esta.NuevoEstado == "asistencia")
                    ViewData["estados"] = "todos";
                }
                if(settings.CustomVisionUso){
                  if(esta.NuevoEstado == "revequiposeguridad")
                    ViewData["estados"] = "sinsitio";
                }
                if(esta.NuevoEstado == "sitio")
                  ViewData["estados"] = "sinsitio";
                if(esta.NuevoEstado == "atendido")
                  ViewData["estados"] = "sinsitioyatendido";
                ViewData["diff"] = DateTime.Today.Subtract(oper.Hora.Date);
                break;
              case 1: //Hoy es después que evidencia
                ViewData["estados"] = "todos";
                ViewData["diff"] = DateTime.Today.Subtract(oper.Hora.Date);
                break;
            }
          }
        }
      }
      ViewData["customvisionuso"] = (bool)settings.CustomVisionUso;
      ViewData["faceapiuso"] = (bool)settings.FaceApiUso;
      ViewData["personaId"] = this.getOperadorId().Result;
      return View();
    }

    private static string getExtension(string fileName){
       string[] words = fileName.Split(new char[]{'.'});
       if(!(words.Length != 2)){
         return words[1];
       }
       Console.WriteLine("\n\nWARNING: Nombre de archivo {0}\n\tSe utilizó la extensión \"ext\"\n\n", fileName);
       return "ext";
    }

    private string createNameOfFile(IFormFile file, OperadorDTO osDTO, int identificador){
      Random ran = new Random();
      byte[] n = new byte[2];
      ran.NextBytes(n);
      OrdenServicio os = _osRepo.GetByIdOS(osDTO.OrdenServicioId);
      string ext = System.IO.Path.GetExtension(file.FileName);
      return String.Format("{0}{3}{1}{5}{6}-{4}{2}", os.Folio, DateTime.Now.ToString("d", CultureInfo.CreateSpecificCulture("es-ES")), ext, Utilities.Tools.OperadorNuevoEstadoStr(osDTO.NuevoEstado), identificador, n[0], n[1]);
    }

    private string tryGetMetadata(string fileName, Dictionary<string,JObject> metadata){
      JObject value = new JObject();
      if(metadata.TryGetValue(fileName, out value)){
        return value.ToString();
      } else {
        return null;
      }
      return null;
    }

    private string tryGetMetadataBi(string fileName, Dictionary<string, string> metadataBi){
      string value = "";

siges/Views/Operador/CambiarEstado.cshtml
@model siges.Models.Operador
@using siges.Models
@{
  ViewData["Title"] = "Cambiar Estado";
  var ordenServicio = ViewData["ordenServicio"] as OrdenServicio;
  var estados = ViewData["estados"] as string;
  var faceapiuso = (bool)ViewData["faceapiuso"];
  var customvisionuso = (bool)ViewData["customvisionuso"];
}

@section css {
<link rel="stylesheet" type="text/css" href="https://unpkg.com/file-upload-with-preview@4.0.2/dist/file-upload-with-preview.min.css">
}
<div class="container justify-content-center">
  <div class="row d-flex justify-content-center">
    <div class="col-10">
      <div class="">
  <h1>@ordenServicio.Cliente.RazonSocial</h1>
  <p class="lead">@ordenServicio.Ubicacion.Nombre</p>
  <hr class="my-4">
  <p>@ordenServicio.Servicio.Nombre</p>
@estados
  <form id="GuardarEstadoForm" enctype="multipart/form-data" action="@Url.Action("GuardarEstado","Operador")" method="post">
    <div class="card text-center">
      <div class="card-header"><b>@ordenServicio.Folio</b></div>
      <div class="card-body">
        <div class="form-group">
          <label for="NuevoEstadoSelect">Nuevo estado:</label>
          <select size=2 class="form-control" id="NuevoEstadoSelect" name="NuevoEstado" required>
            @if(estados == "todos"){
            @if(faceapiuso){
            <option class="d-flex justify-content-center p-2" value="asistencia" data-toggle="tooltip" data-placement="bottom" title="Foto del rostro de la persona que reporta" data-original-title="Tooltip on bottom"><b>Asistencia</b></option>
            }
            <option class="d-flex justify-content-center p-2" value="sitio" data-toggle="tooltip" data-placement="bottom" title="Foto del lugar donde se hará el servicio" data-original-title="Tooltip on bottom"><b>En sitio</b></option>
            <option class="d-flex justify-content-center p-2" value="reporteInterno" data-placement="bottom" title="Foto para el reporte interno" data-original-title="Tooltip on bottom"><b>Reporte interno</b></option>
            @if(customvisionuso){
            <option class="d-flex justify-content-center p-2" value="revequiposeguridad" data-placement="bottom" title="Foto donde la persona utilice elementos de seguridad" data-original-title="Tooltip on bottom"><b>Revisión equipo seguridad</b></option>
            }
            }else if(estados == "sinsitio"){
            <option class="d-flex justify-content-center p-2" value="noatendido" data-placement="bottom" title="Foto para reportar actividad" data-original-title="Tooltip on bottom"><b>Reportar actividad</b></option>
            <option class="d-flex justify-content-center p-2" value="atendido" data-placement="bottom" title="Foto para reportar actividad" data-original-title="Tooltip on bottom"><b>Terminar día</b></option>
            <option class="d-flex justify-content-center p-2" value="reporteInterno" data-placement="bottom" title="Foto para el reporte interno" data-original-title="Tooltip on bottom"><b>Reporte interno</b></option>
            @if(customvisionuso){
            <option class="d-flex justify-content-center p-2" value="revequiposeguridad" data-placement="bottom" title="Foto donde la persona utilice elementos de seguridad" data-original-title="Tooltip on bottom"><b>Revisión equipo seguridad</b></option>
            }
            }else if(estados == "sinsitioyatendido"){
            <option class="d-flex justify-content-center p-2" value="noatendido" data-placement="bottom" title="Foto para reportar actividad" data-original-title="Tooltip on bottom"><b>Reportar actividad</b></option>
            <option class="d-flex justify-content-center p-2" value="reporteInterno" data-placement="bottom" title="Foto para el reporte interno" data-original-title="Tooltip on bottom"><b>Reporte interno</b></option>
            @if(customvisionuso){
            <option class="d-flex justify-content-center p-2" value="revequiposeguridad" data-placement="bottom" title="Foto donde la persona utilice elementos de seguridad" data-original-title="Tooltip on bottom"><b>Revisión equipo seguridad</b></option>
            }
            } else if(estados == "vacio"){
            <span class="d-flex justify-content-center p-2"><b>Existen evidencias registradas para esta Orden de Servicio.</b></span>
            }
          </select>
        </div>
        <div id="clock" class="clock card-title">loading ...</div>
        <div class="form-group shadow-textarea">
          <textarea class="form-control z-depth-1" id="ComentarioNuevoEstadoTextArea" name="ComentarioNuevoEstado" rows="3" placeholder="    Recuerda seguir la redacción y plantilla de evidencias" required></textarea>
        </div>
        <div class="form-group">


          @*<div class="custom-file">
            <input type="file" class="custom-file-input" id="ArchivosEvidencia" lang="es" name="ArchivosEvidencia" multiple onchange="handleFiles(this.files)">
            <label class="custom-file-label" for="ArchivosEvidencia">Evidencia</label>
            <label for="ArchivosEvidencia">5 archivos máximo / 20MB máximo</label>
          </div>*@

          <br>

          <div class="custom-file-container" data-upload-id="myUniqueUploadId">
            <label class="custom-file-container__image-clear" title="Quitar Imagenes">Quitar imagenes
              <a href="javascript:void(0)" class="custom-file-container__image-clear" title="Quitar Imagenes"><i class="fas fa-times"></i></a>
            </label>
            <label class="custom-file-container__custom-file" >
              <input type="file" class="custom-file-container__custom-file__custom-file-input" accept="*" id="ArchivosEvidencia" name="ArchivosEvidencia" multiple aria-label="Choose File">
              <input type="hidden" name="MAX_FILE_SIZE" value="20971520" />
              <span class="custom-file-container__custom-file__custom-file-control"></span>
            </label>
            <div class="custom-file-container__image-preview"></div>
          </div>


        </div>
        <input name="OrdenServicioId" type="hidden" value="@ordenServicio.Id">
        <input name="PersonaId" type="hidden" value="@ViewData["personaId"]">
        <input type="hidden" id="LastModified" name="LastModified">
        <input type="hidden" name="Hora" id="Hora">
        <input type="hidden" name="Exif" id="Exif">
        <div class="row d-flex justify-content-center">
          <div class="col-6">
            <button id="btnSave" type="submit" class="btn btn-primary btn-lg btn-block" disabled>Guardar</button>
          </div>
        </div>
      </div>
      <div class="card-footer text-muted"><b>@(ordenServicio.EstatusServicio.ToUpper())</b></div>
    </div>
  </form>
</div>
    </div>
  </div>
</div>

<!-- Spinner Modal -->
<div class="modal fade" id="spinnerModalCenter" tabindex="-1" role="dialog" aria-labelledby="spinnerModalCenterTitle" aria-hidden="false" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="spinnerModalCenterTitle">Cargando...</h5>
      </div>
      <div class="modal-body">

        <div class="d-flex justify-content-center text-center">
          <div class="spinner-grow text-warning" role="status" style="width: 4rem; height: 4rem;">
            <span class="sr-only">Loading...</span>
          </div>
        </div>
        <div class="spinner-grow text-primary" role="status">
          <span class="sr-only">Loading...</span>
        </div>
        <div class="text-center">
          <div class="spinner-border" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

<!-- ExcedeMegas Modal -->
<div class="modal fade" id="excedeMegas" tabindex="-1" role="dialog" aria-labelledby="excedeMegasTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="excedeMegasTitle">Exceso de Megabytes</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="jumbotron jumbotron-fluid">
          <div class="container">
            <h1 id="mb" class="display-4"></h1>
            <p class="lead">Favor de seleccionar otro archivo o reducir la cantidad de archivos.</p>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


@section scripts {
<script src="~/lib/Exif/exif-reader.js"></script>
<script src="~/lib/moment-2.22.2/min/moment-with-locales.js"></script>
<script src="https://unpkg.com/file-upload-with-preview@4.0.2/dist/file-upload-with-preview.min.js"></script>
<script>
  var files = new FileUploadWithPreview('myUniqueUploadId', {
    showDeleteButtonOnImages: true,
    text: {
      chooseFile: 'Evidencias',
      browse: 'Seleccionar archivos',
      selectedCount: 'archivos seleccionados',
    },
    presetFiles: [],
  })

  /*
  * Valida si está seleccionado un estado y si está capturado el comentario del cambio de estado
  *
  * */
  document.querySelector('button.btn-primary[type="submit"]').addEventListener('click', e => {
    e.preventDefault()
    if(document.getElementById('NuevoEstadoSelect').value === '' || document.getElementById('ComentarioNuevoEstadoTextArea').value === ''){
      document.getElementById('spinnerModalCenterTitle').innerText = 'Falta información requerida para continuar...';
      if(document.getElementById('NuevoEstadoSelect').value === ''){
        document.getElementById('spinnerModalCenter').removeAttribute('data-backdrop');
        document.getElementById('spinnerModalCenter').removeAttribute('data-keyboard');
        document.querySelector('#spinnerModalCenter .modal-body').innerHTML = '<div class="alert alert-warning" role="alert"><p align="center"> Favor de seleccionar un estado </p></div>';
        $('#spinnerModalCenter').modal('toggle');
      } else if(document.getElementById('ComentarioNuevoEstadoTextArea').value === ''){
        document.getElementById('spinnerModalCenter').removeAttribute('data-backdrop');
        document.getElementById('spinnerModalCenter').removeAttribute('data-keyboard');
        document.querySelector('#spinnerModalCenter .modal-body').innerHTML = '<div class="alert alert-warning" role="alert"><p align="center"> Favor de redactar información adicional al reporte.  </p></div>';
        $('#spinnerModalCenter').modal('toggle');
      }
    } else {
      document.getElementById('spinnerModalCenter').setAttribute('data-keyboard','false');
      document.getElementById('spinnerModalCenter').setAttribute('data-backdrop','static');
      document.getElementById('spinnerModalCenterTitle').innerText = 'Cargando...';
      document.querySelector('#spinnerModalCenter .modal-body').innerHTML = '<div class="text-center"><div class="spinner-border text-primary m-5" role="status"><span class="sr-only">Loading...</span></div></div>';
      @*document.getElementById('ArchivosEvidencia').value = files.cachedFileArray;*@
      $('#spinnerModalCenter').modal('toggle');
      $('#Hora').val(moment().format("YYYY MM DD HH:mm:ss"));
      $('#Exif').val(Tags);
      document.getElementById('GuardarEstadoForm').submit();
    }
  });

  document.getElementById('inputMultiFile');
  var lastModified = {};

  function handleFiles(files){
    var fileList = files;
    for(let i = 0; i < fileList.length; i++){
      var folio = document.querySelector('div.card-header').firstChild.innerText;
      var ext = fileList[i].name.substring(files[i].name.lastIndexOf('.'));
      var name = folio+i+ext;
      var file = fileList[i].slice();
    }
  }

  $(document).ready(function(){
    if(document.getElementById('MenuCambiarEstadoOperador') != null)
      document.getElementById('MenuCambiarEstadoOperador').setAttribute('style', 'display: none');
  });
  

  function update() {
    $('#clock').html(moment().locale('es').format('D MMMM YYYY H:mm:ss'));
  }
  setInterval(update, 1000);

  const Tags = [];
  var archivosAsubir = [];

  const VALID_EXT = ["JPEG", "JPG", "BMP", "PNG"];

  $("#ArchivosEvidencia").on("change", (event)=>{
    const EXTEN = $("#ArchivosEvidencia").prop('files')[0].name.split('.');
    const VALID = VALID_EXT.includes(EXTEN[EXTEN.length - 1].toUpperCase());
    if(!VALID){
      $("#btnSave").attr('disabled', 'true');
      Swal.fire({
        icon: 'error',
        title: '¡Error!',
        confirmButtonColor: "#67E7CF",
        confirmButtonText:"Aceptar",
        text: `Archivo no valido`
      });
    }
    else{
    files = event.target.files;
    console.log({files});
    for(const file of files ){
      $("#btnSave").removeAttr('disabled');
      archivosAsubir.push(file);
      console.log({file});
      let reader = new FileReader();
      const name = file.name;
      console.log({name});
      reader.onload = function (readerEvent) {
        try {
            let tags = ExifReader.load(readerEvent.target.result);
            delete tags['MakerNote'];
            tags['FileName'] = name; 
            //Tags.push(tags);
            Tags.push(JSON.stringify(tags));
            console.log({Tags});
        } catch (error) {
            console.log(error.toString());
        }
      };
      reader.readAsArrayBuffer(file);
    }
    }
})

document.getElementById('ArchivosEvidencia').addEventListener('click', e => {
  document.querySelector('a.custom-file-container__image-clear').click();
  console.log({e});
});

</script>
}

siges/Views/Operador/ReporteActividad.cshtml
@using siges.Models
@using System
@using System.Collections.Generic
@{
List<Operador> osAtendido = ViewData["osAtendido"] as List<Operador>;
}

<div class="jumbotron">
  <h1 class="display-4">@(osAtendido.Count > 0 ? osAtendido[0].OrdenServicio.Cliente.RazonSocial : "Sin Reporte de actividad")</h1>
  <p class="lead">@(osAtendido.Count > 0 ? osAtendido[0].OrdenServicio.Ubicacion.Nombre : "para esta Orden de Servicio")</p>
  <hr class="my-4">
  <p>@(osAtendido.Count > 0 ? osAtendido[0].OrdenServicio.Servicio.Nombre : "")</p>

  <div class="row p-2">
    <div class="col-md-12">
      @if(osAtendido != null && osAtendido.Count > 0){
      @foreach ( var osAten in osAtendido) {
      @foreach (var estado in osAten.EstadoN as List<Operador.Estado>) {
      <div class="p-3">
        <div class="card text-center">
          <div class="card-header">@osAten.Hora.ToString("D")</div>
          <div class="card-body">
            <h5 class="card-title">@(estado.NuevoEstado == "sitio" ? "En sitio:" : (estado.NuevoEstado=="noatendido"?"Reporte de actividad:":"Atendido:"))</h5>
            <p class="card-text">@estado.ComentarioNuevoEstado</p>
            @if(estado.ArchivosEvidencia != null && estado.ArchivosEvidencia.Count > 0){
            @foreach(var archivo in estado.ArchivosEvidencia as List<Operador.Estado.Archivo>){
            <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action( "MostrarArchivo", "Operador", new{@osId=@osAten.OrdenServicio.Id, @operadorEstadoId=@estado.Id, @operadorEstadoArchivoId = @archivo.Id})'">@archivo.Name</button>
            }
            }
          </div>
          <div class="card-footer text-muted"><b>@(String.Format("{0} {1}", @osAten.Persona.Nombre, @osAten.Persona.Paterno).ToUpper())</b></div>
        </div>
      </div>
      }
      }
      }
    </div>
  </div>

  <button class="btn btn-success btn-lg" type="button" onclick="location.href='@Url.Action( "Index", "Operador")'" >Regresar</button>
</div>