siges/Models/Administracion.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;

namespace siges.Models {
  public class Administracion {
    public int Id {get; set;}
    public bool Estatus {get; set;}
    public int OrdenServicioId {get; set;}
    public int PersonaId {get; set;}
    public DateTime FechaAdministrativa {get; set;}
    public string FacturaFolio {get; set;}
    public DateTime FacturaFecha {get; set;}
  }
}

siges/Controllers/AdministracionController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using siges.DTO;
using siges.Models;
using siges.Repository;
using siges.Utilities;
using Newtonsoft.Json.Linq;
using System.Globalization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using siges.Areas.Identity.Data;

namespace siges.Controllers
{
  [Authorize(Roles = "Administración, SuperUser")]
  public class AdministracionController : Controller
  {
    private readonly IConfiguracionServicioRepository _csRepo;
    private readonly IContratoRepository _cRepo;
    private readonly IServicioRepository _sRepo;
    private readonly ILineaNegocioRepository _lnRepo;
    private readonly IOrdenServicioRepository _osRepo;
    private readonly IUbicacionRepository _uRepo;
    private readonly IPersonaRepository _pRepo;
    private readonly IInsumoRepository _iRepo;
    private readonly IActivoFijoRepository _afRepo;
    private readonly IClienteRepository _clRepo;
    private readonly IBitacoraRepository _bRepo;
    private readonly IOperador _operRepo;
    private readonly UserManager<RoatechIdentityUser> _userManager;
    private readonly RoleManager<IdentityRole> _roleManager;
    private readonly IEmailConfiguration _emailConf;
    private readonly IAdministracion _admRepo;
    private readonly IBitacoraEstatusRepository _beRepo;
    private readonly Settings settings;
        private readonly IIndexListOSDTORepository _indexListOSDTORepo;
    private String LoggedUser;

    public AdministracionController(IIndexListOSDTORepository ilosdtor, IConfiguracionServicioRepository csRepo, IContratoRepository cRepo, IServicioRepository sRepo, ILineaNegocioRepository lnRepo, IOrdenServicioRepository osRepo, IUbicacionRepository uRepo, IPersonaRepository pRepo, IInsumoRepository iRepo, IActivoFijoRepository afRepo, IClienteRepository clRepo, IBitacoraRepository bRepo, IOperador operRepo, UserManager<RoatechIdentityUser> um, RoleManager<IdentityRole> rm, IEmailConfiguration emailConf, IAdministracion admRepo, IBitacoraEstatusRepository beRepo, ISettingsRepository setRepo)
    {
      _indexListOSDTORepo = ilosdtor;
      _csRepo = csRepo;
      _cRepo = cRepo;
      _sRepo = sRepo;
      _lnRepo = lnRepo;
      _osRepo = osRepo;
      _uRepo = uRepo;
      _pRepo = pRepo;
      _iRepo = iRepo;
      _afRepo = afRepo;
      _clRepo = clRepo;
      _bRepo = bRepo;
      _operRepo = operRepo;
      _userManager = um;
      _roleManager = rm;
      _emailConf = emailConf;
      _admRepo = admRepo;
      _beRepo = beRepo;
      settings = setRepo.GetByVersion("DAMSA");
    }

    public IActionResult Index()
    {
      List<OrdenServicio> ordSer = _osRepo.GetAll(true).ToList();
      JsonSerializerSettings jsonSettings = new JsonSerializerSettings();
      jsonSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
      jsonSettings.NullValueHandling = NullValueHandling.Ignore;
      string output = JsonConvert.SerializeObject(ordSer, jsonSettings);
      ViewData["ordenesServicio"] = output;
      return View();
    }

    public IActionResult IndexListOS()
    {
      List<OrdenServicio> _all = new List<OrdenServicio>();
      foreach (OrdenServicio os in _osRepo.GetAll(true).OrderByDescending(r => r.Id).ToList())
      {
        if (os.EstatusServicio == "finalizado" || os.EstatusServicio == "cobrado" || os.EstatusServicio == "nocobrado" || os.EstatusServicio == "facturado" || os.EstatusServicio == "cancelado")
          _all.Add(os);
      }
      List<Administracion> _facOS = _admRepo.GetAll(true).ToList();
      Dictionary<int, Administracion> _fact = new Dictionary<int, Administracion>();
      foreach(OrdenServicio os in _all){
        foreach(Administracion adm in _facOS){
          if(os.Id == adm.OrdenServicioId)
            _fact[os.Id] = adm;
        }
      }
      ViewData["ordenes"] = _indexListOSDTORepo.GetAllOS().Where(o => o.EstatusServicio == "finalizado" || o.EstatusServicio == "cobrado" || o.EstatusServicio == "nocobrado" || o.EstatusServicio == "facturado" || o.EstatusServicio == "cancelado").OrderByDescending(o => o.Id).ToList();
      ViewData["facturas"] = _fact;
      return View("~/Views/Administracion/ListOrdenServicio.cshtml");
    }

    /* Editar Orden de servicios */
    public IActionResult IndexEditOS(int ordenId)
    {
      OrdenServicio eOS = _osRepo.GetByIdOS(ordenId);
      List<Cliente> _allcl = _clRepo.GetAll(true).ToList();
      List<Contrato> _allc = _cRepo.GetContratoByCliente(eOS.Cliente.Id).ToList();
      List<Ubicacion> _allu = _uRepo.getUbicacionesByCliente(eOS.Cliente.Id).ToList();
      List<Servicio> _alls = _sRepo.GetAll(true).ToList();
      List<LineaNegocio> _allln = _lnRepo.GetAll(true).ToList();
      List<Operador> _evidencias = _operRepo.GetAtencionServicio(ordenId).ToList();
      List<BitacoraEstatus> _allbe = _beRepo.GetAllByOSId(ordenId).ToList();
      ViewData["orden"] = eOS;
      ViewData["clientes"] = _allcl;
      ViewData["contratos"] = _allc;
      ViewData["servicios"] = _alls;
      ViewData["lineas"] = _allln;
      ViewData["ubicaciones"] = _allu;
      ViewData["evidencias"] = _evidencias;
      ViewData["cambiosEstado"] = _allbe;
      Dictionary<int, Persona> personas = new Dictionary<int, Persona>();
      foreach (Operador oper in _evidencias)
      {
        if (oper.Persona.Id > 0)
        {
          personas.Add(oper.Id, (Persona)_pRepo.GetById(oper.Persona.Id));
        }
      }
      ViewData["personas"] = personas; 
      return View("~/Views/Administracion/EditOrdenServicio.cshtml");
    }

    [HttpPost]
    public IActionResult CapturaDatosFactura(CapturaDatosFacturaDTO cdf){
      OrdenServicio os = _osRepo.GetById(cdf.OrdenServicioId);
      os.EstatusServicio = "facturado";
      _osRepo.Update(os);
      Administracion adm = new Administracion(){
        Estatus = true,
                OrdenServicioId = cdf.OrdenServicioId,
                PersonaId = _pRepo.GetByEmail(this.User.Identity.Name).Single().Id,
                FechaAdministrativa = DateTime.Now,
                FacturaFolio = cdf.FacturaFolio,
                FacturaFecha = cdf.FacturaFecha};
      _admRepo.Insert(adm);
      if(siges.Utilities.Tools.ValidaCamposCompletosOSyP(os, _pRepo.GetByEmail(this.User.Identity.Name).Single())){
        Notifica notifica = new Utilities.Notifica(_emailConf, _userManager, _roleManager, "FACTURADA", new MimeKit.Multipart("Mixed"), this.User.Identity.Name.ToString(), settings);
        List<Operador> osAtendido = _operRepo.GetAtencionServicio(os.Id).ToList();
        notifica.OrdenServicioNotifica("ventas", "factura", osAtendido, osAtendido[0].OrdenServicio, _beRepo.GetFinalizadoDescriptionByOSid(osAtendido[0].OrdenServicio.Id).ToList()[0].Description);
        notifica.OrdenServicioNotifica("supervisor", "factura", osAtendido, osAtendido[0].OrdenServicio, _beRepo.GetFinalizadoDescriptionByOSid(osAtendido[0].OrdenServicio.Id).ToList()[0].Description);
      }
      return RedirectToAction("IndexListOS");
    }

    public IActionResult CapturaComentario(BitacoraEstatusDTO be){
      OrdenServicio os = _osRepo.GetByIdOS(be.OrdenServicioId);
      os.EstatusServicio = be.A;
      _osRepo.Update(os);
      _beRepo.Insert(new BitacoraEstatus(){
          Os = os,
          Folio = os.Folio.ToUpper(),
          QuienCambia = _pRepo.GetByEmail(this.User.Identity.Name).Single(),
          Email = this.User.Identity.Name.ToUpper(),
          De = be.De.ToUpper(),
          A = be.A.ToUpper(),
          FechaAdministrativa = DateTime.Now,
          Description = be.MotivoCambio });
      return RedirectToAction("IndexEditOS", "Servicio", new {ordenId=be.OrdenServicioId});
    }

    [HttpPost]
    public IActionResult EditOS(OrdenServicioDTO nOS)
    {
      OrdenServicio os = _osRepo.GetByIdOS(nOS.Id);
      os.EstatusServicio = nOS.EstatusServicio;
      //if(suwus.Utilities.Tools.ValidaCamposCompletosOSyP(os, _pRepo.GetByEmail(this.User.Identity.Name))){
        Console.WriteLine("\n\n\n{0}\n\n\n", os.EstatusServicio, this);
        /*if(os.EstatusServicio == "cobrado"){
          Notifica notifica = new Utilities.Notifica(_emailConf, _userManager, _roleManager, "COBRADA", new MimeKit.Multipart("Mixed"), this.User.Identity.Name.ToString(), settings);
          List<Operador> osAtendido = _operRepo.GetAtencionServicio(os.Id).ToList();
          notifica.OrdenServicioNotifica("ventas", "cobrado", osAtendido, os, _beRepo.GetFinalizadoDescriptionByOSid(os.Id).ToList()[0].Description);
          notifica.OrdenServicioNotifica("supervisor", "cobrado", osAtendido, os, _beRepo.GetFinalizadoDescriptionByOSid(os.Id).ToList()[0].Description);
          Console.WriteLine("\n\n{0} {1} {2} {3} {4} {5}\n\n", os.Folio, os.Cliente.RazonSocial, os.Contrato.Nombre, os.Ubicacion.Nombre, os.LineaNegocio.Nombre, os.Tipo);
        }
        if(os.EstatusServicio == "nocobrado"){
          Notifica notifica = new Utilities.Notifica(_emailConf, _userManager, _roleManager, "NO COBRADA", new MimeKit.Multipart("Mixed"), this.User.Identity.Name.ToString(), settings);
          List<Operador> osAtendido = _operRepo.GetAtencionServicio(os.Id).ToList();
          notifica.OrdenServicioNotifica("todos", "nocobrado", osAtendido, os, _beRepo.GetFinalizadoDescriptionByOSid(os.Id).ToList()[0].Description);
          Console.WriteLine("\n\n{0} {1} {2} {3} {4} {5}\n\n", os.Folio, os.Cliente.RazonSocial, os.Contrato.Nombre, os.Ubicacion.Nombre, os.LineaNegocio.Nombre, os.Tipo);
        }
        if(os.EstatusServicio == "cancelado"){
          Notifica notifica = new Utilities.Notifica(_emailConf, _userManager, _roleManager, "CANCELADA", new MimeKit.Multipart("Mixed"), this.User.Identity.Name.ToString(), settings);
          List<Operador> osAtendido = _operRepo.GetAtencionServicio(os.Id).ToList();

siges/Views/Administracion/ListDeletedOrdenServicio.cshtml
@using siges.Models
@{
    ViewData["Title"] = "Administración para órdenes de servicio eliminadas";
    ViewData["TitlePage"] = "Administración para órdenes de servicio eliminadas";
}


<div class="container">
    <div class="row">
        <div class="col">
            <h2>&Oacute;rdenes de Servicio Eliminadas</h2>
        </div>
        <div class="col align-self-center text-right">
            <a class="btn bg-blue marg-Float float" href='@Url.Action( "IndexListOS", "Administracion")' data-toggle="tooltip" data-placement="bottom" title="Regresar" data-original-title="Tooltip on bottom"><i class="fas fa-arrow-left"></i></a>
        </div>
    </div>
<div class="row">
<table id="tOrdenes" data-toggle="table" data-search="true" data-show-columns="false" data-pagination="true" data-locale="es-MX" data-classes="table table-hover" data-page-size="5" data-show-footer="true">
    <thead>
        <tr>
            <th data-field="id" data-visible="false">ID</th>
            <th data-field="folio" data-sortable="true" data-width="10%">Folio</th>
            <th data-field="fecha" data-sortable="true" data-width="10%">Fecha</th>
            <th data-field="cliente" data-sortable="true" data-width="10%">Cliente</th>
            <th data-field="documento" data-sortable="true" data-width="20%">Documento</th>
            <th data-field="ubicacion" data-sortable="true" data-width="20%">Ubicaci&oacute;n</th>
            <th data-field="servicio" data-sortable="true" data-width="10%">Servicio</th>
            <th data-field="estatus" data-sortable="true" data-width="10%">Estatus</th>
            <th data-width="5%">Restaurar</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var orden in ViewData["ordenes"] as List<OrdenServicio>)
        {
            <tr>
                <td>@orden.Id</td>
                <td>@orden.Folio</td>
                <td>@(orden.FechaInicio.HasValue ? orden.FechaInicio.Value.Date.ToString("dd/MM/yyyy") : "Sin fecha registrada" )</td>
                <td>@orden.Cliente.RazonSocial</td>
                <td>@orden.Contrato.Nombre</td>
                <td>@orden.Ubicacion.Nombre</td>
                <td>@orden.Servicio.Nombre</td>
                <td>@orden.EstatusServicio</td>
                <td>
                    <div class="row">
                        <div class="col">
                            <span data-toggle="tooltip" data-placement="top" title="Restaurar">
                                <button class="btn btn-success float_Table"data-toggle="modal" data-target="#restoreOrdenModal" data-s-id="@orden.Id" data-s-folio="@orden.Folio">
                                    <i class="fas fa-file-import"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>
</div>


@section Modals {
  
    <div id="restoreOrdenModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Restaurar &oacute;rden de servicio</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>¿Estas seguro de que deseas restaurar la &oacute;rden de servicio con el folio <span id="delNo"></span>?</p>
                </div>
                <div class="modal-footer">
                    <button id="resBtn" type="button" class="btn btn-success">S&iacute;</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>

}

@section scripts {
    <script src="~/js/listDeletedOrdenServicio.js"></script>
}

siges/Views/Administracion/ListOrdenServicio.cshtml
@using siges.DTO
@using siges.Models
@using System
@using System.Globalization
@using System.Collections.Generic
@{
    ViewData["Title"] = "Órdenes de Servicio";
    ViewData["TitlePage"] = "Órdenes de Servicio";
    Dictionary<int, Administracion> facturas = ViewData["facturas"] as Dictionary<int,Administracion>;
    Administracion factura = new Administracion();
}


<div class="container">
<div class="row">
    <div class="col">
        <h2>&Oacute;rdenes de Servicio</h2>
    </div>
    <div class="col align-self-center text-right">
        @*<button id="filtrarBtn" type="button" onclick="openFilterMenu()" class="btn btn-primary">Filtrar</button>*@
        <a class="btn bg-yellow margR-30px float" href='@Url.Action("Index", "Administracion")' data-toggle="tooltip" data-placement="bottom" title="Calendario" data-original-title="Tooltip on bottom"><i class="fas fa-calendar-alt"></i></a>
        @* <a class="btn btn-danger marg-Float float" href='@Url.Action( "IndexListDOS", "Administracion")' data-toggle="tooltip" data-placement="bottom" title="Órdenes de Servicio Eliminadas" data-original-title="Tooltip on bottom"><i class="fas fa-file-excel"></i></a> *@
    </div>
</div>
<div class="row">
    <table id="tOrdenes" data-toggle="table" data-search="true" data-show-columns="false" data-pagination="true" data-locale="es-MX" data-classes="table table-hover" data-page-size="5"  data-page-list="[5,10,25]" data-show-footer="true" data-sort-name="folio">
    <thead>
        <tr>
            <th data-field="id" data-visible="false">ID</th>
            <th data-field="folio" data-sortable="true">Folio</th>
            <th data-field="fecha" data-sortable="true" data-filter-control="input">Fecha</th>
            <th data-field="cliente" data-sortable="true" data-filter-control="select">Cliente</th>
            <th data-field="documento" data-sortable="true" data-filter-control="select">Documento</th>
            <th data-field="ubicacion" data-sortable="true" data-filter-control="select">Ubicaci&oacute;n</th>
            <th data-field="servicio" data-sortable="true" data-filter-control="select">Servicio</th>
            <th data-field="estatus" data-sortable="true" data-filter-control="select">Estatus</th>
            <th>Editar</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var orden in ViewData["ordenes"] as List<IndexListOSDTO>)
        {
            <tr>
                <td>@orden.Id</td>
                <td>@orden.Folio</td>
                <td>@(orden.FechaInicio.HasValue ? orden.FechaInicio.Value.Date.ToString("dd/MM/yyyy") : "Sin fecha registrada" )</td>
                <td>@orden.Cliente</td>
                <td>@orden.Contrato / @orden.ContratoTipo</td>
                <td>@orden.Ubicacion</td>
                <td>@orden.Servicio</td>
                <td style="text-transform: capitalize;">@(orden.EstatusServicio == "finalizado" ? "Finalizado" : orden.EstatusServicio == "cobrado" ? "Cobrado" : orden.EstatusServicio == "nocobrado" ? "No cobrado" : orden.EstatusServicio == "cancelado" ? "Cancelado" : orden.EstatusServicio == "facturado" ? "Facturado" : "Indefinido") @(orden.EstatusServicio == "facturado" ? facturas.TryGetValue(orden.Id, out factura) ? "/ " + factura.FacturaFolio + " - " + factura.FacturaFecha.ToString("D", CultureInfo.CreateSpecificCulture("es-ES")) : "/ Sin factura" : "")</td>
                <td>
                    <a href="@Url.Action( "IndexEditOS", "Administracion" , new { ordenId=@orden.Id })" class="btn btn-success float_Table" data-toggle="tooltip" data-placement="bottom" title="Editar" data-original-title="Tooltip on bottom"><i class="fas fa-edit"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>
</div>

@section Modals {

    <div id="deleteOrdenModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Eliminar &oacute;rden de servicio</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>¿Estas seguro de que deseas eliminar la &oacute;rden de servicio con el folio <span id="delNo"></span>?</p>
                </div>
                <div class="modal-footer">
                    <button id="delBtn" type="button" class="btn btn-danger">S&iacute;</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>

}

@section scripts {
    <script src="~/js/listOrdenServicio.js"></script>
}