siges/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace siges.Models
{
    public class Persona : IComparable<Persona>
    {
        public int Id { get; set; }

        [DisplayName("Nombre(s)")]
        [StringLength(30, ErrorMessage = "Longitud máxima requerida, {1} caracteres.")]
        public string Nombre { get; set; }

        [DisplayName("Apellido Paterno")]
        [StringLength(30, ErrorMessage = "Longitud máxima requerida, {1} caracteres.")]
        public string Paterno { get; set; }

        [DisplayName("Apellido Materno")]
        [StringLength(30, ErrorMessage = "Longitud máxima requerida, {1} caracteres.")]
        public string Materno { get; set; }

        [MinLength(13, ErrorMessage = "Mínimo {1} caracteres.")]
        [StringLength(13, ErrorMessage = "Longitud requerida, {1} caracteres.")]
        [MaxLength(13, ErrorMessage = "Máximo {1} caracteres.")]
        [RegularExpression(@"^[A-Z]{4}\d{6}\w{3}$", ErrorMessage = "4 consonantes mayúsculas, 6 dígitos y 3 caracteres alfanuméricos.")] //[RegularExpression(@"^\$?\d+(\.(\d{2}))?$")]
        public string RFC { get; set; }

        [MinLength(18, ErrorMessage = "El campo CURP debe tener una longitud mínima de '{1}'.")]
        [StringLength(18)]
        [MaxLength(18)]
        [RegularExpression(@"^[A-Z]{4}\d{6}[MH][A-Z]{5}\w{2}$", ErrorMessage = "4 consonantes, 6 dígitos, 6 consonantes y 2 caracteres alfanuméricos.")] //[RegularExpression(@"^\$?\d+(\.(\d{2}))?$")]
        public string CURP { get; set; }

        public string Email { get; set; }

        public Direccion Dir { get; set; }

        [DisplayName("Clave de Empleado")]
        public string ClaveEmpleado { get; set; }

        [MinLength(10)]
        [StringLength(10)]
        [MaxLength(10)]
        [DisplayName("Teléfono")]
        public string Telefono { get; set; }

        [MinLength(10)]
        [StringLength(10)]
        [MaxLength(10)]
        [DisplayName("Celular")]
        public string TelefonoContacto { get; set; }
        public bool Estatus { get; set; }

        [StringLength(30, ErrorMessage = "Longitud máxima requerida, {1} caracteres.")]
        [DisplayName("Categoría")]
        public string Categoria { get; set; }

        [StringLength(50, ErrorMessage = "Longitud máxima requerida, {1} caracteres.")]
        [DisplayName("Puesto")]
        public string Puesto { get; set; }

        [StringLength(150, ErrorMessage = "Longitud máxima requerida, {1} caracteres.")]
        [DisplayName("Dirección")]
        public string Direccion { get; set; }

        [StringLength(50, ErrorMessage = "Longitud máxima requerida, {1} caracteres.")]
        [DisplayName("Entidad Federativa")]
        public string EntidadFederativa { get; set; }

        [StringLength(50, ErrorMessage = "Longitud máxima requerida, {1} caracteres.")]
        [DisplayName("Municipio/Alcaldía")]
        public string Municipio { get; set; }

        [Column(TypeName = "decimal(18, 2)")]
        [DataType(DataType.Currency)]
        public int Sueldo { get; set; }

        [StringLength(200, ErrorMessage = "Longitud máxima requerida, {1} caracteres.")]
        [DisplayName("Campo opcional 1")]
        public string Opcional1 { get; set; }

        [StringLength(200, ErrorMessage = "Longitud máxima requerida, {1} caracteres.")]
        [DisplayName("Campo opcional 2")]
        public string Opcional2 { get; set; }

        [StringLength(30, ErrorMessage = "Longitud máxima requerida, {1} caracteres.")]
        [DisplayName("Adscripción")]
        public string Adscripcion { get; set; }

        [DisplayName("Fotografía")]
        public byte[] Fotografia { get; set; }
        [ScaffoldColumn(false)]
        public int UsuarioId { get; set; }
        [ScaffoldColumn(false)]
        public int PerfilId { get; set; }
        public string FaceApiId { get; set; }
        public int FaceApiCount { get; set; }
        public string Token { get; set; }

        public int CompareTo(Persona p)
        {
            if (p == null)
                return 1;
            else
                return (this.Nombre + this.Paterno + this.Materno).CompareTo(p.Nombre + p.Paterno + p.Materno);
        }
    }
}

siges/Controllers/PersonasController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

using siges.Data;
using siges.DTO;
using siges.Models;
using siges.Repository;

namespace siges.Controllers {
  public class PersonasController : Controller {
    private readonly ApplicationDbContext _context;
    private readonly IBitacoraRepository _bRepo;
    private readonly IPersonaRepository _pRepo;
    private readonly Settings settings;
    private String LoggedUser;

    public PersonasController(ApplicationDbContext context, IBitacoraRepository bRepo, IPersonaRepository pRepo, ISettingsRepository _set) {
      _context = context;
      _bRepo = bRepo;
      _pRepo = pRepo;
      settings = _set.GetByVersion("DAMSA");
    }

    // GET: Personas
    [Authorize(Roles = "Supervisor, SuperUser")]
    public async Task<IActionResult> Index() {
      if(User.Identity.IsAuthenticated){
        return View(await _context.Persona.Where(r => r.Estatus == true).ToListAsync());
      }
      return View();
    }

    public IActionResult IndexListDP(){
      if(User.Identity.IsAuthenticated){
        ViewData["persona"] = _pRepo.GetAll(false).ToList();
      }
      return View("~/Views/Personas/PersonsDeleted.cshtml");
    }
    [HttpPost]
    public IActionResult UpdateDP(int pid){
      if(User.Identity.IsAuthenticated){
        if(pid != null && pid > 0){
          try{
            Persona nP = _pRepo.GetById(pid);
            nP.Estatus = true;
            _pRepo.Update(nP);
            LoggedUser = this.User.Identity.Name;
            _bRepo.Insert(new Bitacora() { UserId = LoggedUser, EventDate = DateTime.Now, Event = "Update", Section = "Persona", Description = "Persona no. " + nP.Id + " actualizada." });
            return Json(new{success=true});
          } catch (Exception e) {
            return Json(new{success=false, data=e});
          }
        }
        return NotFound();
      }
      return View();
    }

    // GET: Personas/Details/5
    [Authorize(Roles = "Supervisor, SuperUser")]
    public async Task<IActionResult> Details(int? id) {
      if(User.Identity.IsAuthenticated){
        if (id != null && id > 0) {
          try{
            var persona = await _context.Persona.FirstOrDefaultAsync(m => m.Id == id);
            if (persona == null) {
              return NotFound();
            }
            return Json(new{success=true, data=persona});
          } catch (Exception e){
            return Json(new{success=false, data=e});
          }
        }
        return NotFound();
      }
      return View();
    }

    // POST: Personas/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    //[ValidateAntiForgeryToken]
    [HttpPost]
    public async Task<IActionResult> Create(IFormFile fotografia, [Bind("Id,Nombre,Paterno,Materno,RFC,CURP,Email,ClaveEmpleado,Telefono,TelefonoContacto,Estatus,Puesto,Categoria,Direccion,EntidadFederativa,Municipio,Sueldo,Opcional1,Opcional2,Adscripcion,FaceApiId,FaceApiCount")] PersonaDTO persona) {
      // if(User.Identity.IsAuthenticated){
      //   if(!String.IsNullOrEmpty(persona.Nombre) && !String.IsNullOrEmpty(persona.Paterno) && !String.IsNullOrEmpty(persona.Materno) && !String.IsNullOrEmpty(persona.RFC) && !String.IsNullOrEmpty(persona.Email) && !String.IsNullOrEmpty(persona.Puesto) && !String.IsNullOrEmpty(persona.Categoria)){
      //     if (ModelState.IsValid) {
      try {
        Persona p = new Persona();
        p.Nombre = persona.Nombre;
        p.Paterno = persona.Paterno;
        p.Materno = persona.Materno;
        p.RFC = persona.RFC;
        p.CURP = persona.CURP;
        p.Email = persona.Email;
        p.ClaveEmpleado = persona.ClaveEmpleado;
        p.Telefono = persona.Telefono;
        p.TelefonoContacto = persona.TelefonoContacto;
        p.Categoria = persona.Categoria;
        p.Puesto = persona.Puesto;
        p.Direccion = persona.Direccion;
        p.EntidadFederativa = persona.EntidadFederativa;
        p.Municipio = persona.Municipio;
        p.Sueldo = persona.Sueldo;
        p.Adscripcion = persona.Adscripcion;
        p.Opcional1 = persona.Opcional1;
        p.Opcional2 = persona.Opcional2;
        p.Estatus = true;
        p.FaceApiId = "SINFACEAPIID";
        if(settings.FaceApiUso){
          p.FaceApiCount = persona.FaceApiCount;
        }
        if(fotografia != null && fotografia.Length > 0){
          using(var memoryStream = new MemoryStream()){
            await fotografia.CopyToAsync(memoryStream);
            p.Fotografia = memoryStream.ToArray();
          }
        }  
        _context.Add(p);
        await _context.SaveChangesAsync();
        LoggedUser = this.User.Identity.Name;
        _bRepo.Insert(new Bitacora() { UserId = LoggedUser, EventDate = DateTime.Now, Event = "Insert", Section = "Persona", Description = "Persona no. " + persona.Id + " agregada." });
        return Json(new{success=true});
      } catch (Exception e){
        return Json(new{success=false, data=e});
      }
      //     }
      //   }
      //   return NotFound();
      // }
      // return View();
    }

    // POST: Personas/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    //[ValidateAntiForgeryToken]
    [HttpPost]
    [Authorize(Roles = "Supervisor, SuperUser")]
    public async Task<IActionResult> Edit(int id, IFormFile fotografia, [Bind("Id,Nombre,Paterno,Materno,RFC,CURP,Email,ClaveEmpleado,Telefono,TelefonoContacto,Estatus,Puesto,Categoria,Direccion,EntidadFederativa,Municipio,Sueldo,Opcional1,Opcional2,Adscripcion,FaceApiId,FaceApiCount")] PersonaDTO persona) {

      //if(id == persona.Id && !String.IsNullOrEmpty(persona.Nombre) && !String.IsNullOrEmpty(persona.Paterno) && !String.IsNullOrEmpty(persona.Materno) && !String.IsNullOrEmpty(persona.RFC) && !String.IsNullOrEmpty(persona.Email) && !String.IsNullOrEmpty(persona.Puesto) && !String.IsNullOrEmpty(persona.Categoria)){
         //if (ModelState.IsValid) {
      try {
        Persona p = _pRepo.GetById(persona.Id);
        p.Nombre = persona.Nombre;
        p.Paterno = persona.Paterno;
        p.Materno = persona.Materno;
        p.RFC = persona.RFC;
        p.CURP = persona.CURP;
        p.Email = persona.Email;
        p.ClaveEmpleado = persona.ClaveEmpleado;
        p.Telefono = persona.Telefono;
        p.TelefonoContacto = persona.TelefonoContacto;
        p.Categoria = persona.Categoria;
        p.Puesto = persona.Puesto;
        p.Direccion = persona.Direccion;
        p.EntidadFederativa = persona.EntidadFederativa;
        p.Municipio = persona.Municipio;
        p.Sueldo = persona.Sueldo;
        p.Adscripcion = persona.Adscripcion;
        p.Opcional1 = persona.Opcional1;
        p.Opcional2 = persona.Opcional2;
        if(settings.FaceApiUso){
          p.FaceApiId = String.IsNullOrEmpty(p.FaceApiId) ? "SINFACEAPIID" : p.FaceApiId;
          p.FaceApiCount = p.FaceApiCount > 0 ? p.FaceApiCount : 0;
        }
        if(fotografia != null && fotografia.Length > 0){
          using(var memoryStream = new MemoryStream()){
            await fotografia.CopyToAsync(memoryStream);
            p.Fotografia = memoryStream.ToArray();
          }
        } else {
          p.Fotografia = p.Fotografia;
        }
        p.Estatus = true;
        _context.Update(p);
        await _context.SaveChangesAsync();
        LoggedUser = this.User.Identity.Name;
        _bRepo.Insert(new Bitacora() { UserId = LoggedUser, EventDate = DateTime.Now, Event = "Update", Section = "Persona", Description = "Persona no. " + persona.Id + " actualizada." });
        return Json(new{success=true});
      } catch (DbUpdateConcurrencyException e) {
             if (!PersonaExists(persona.Id)) {
               return NotFound();
             } else {
               return Json(new{success=false, data=e});
             }
           }
         //}
         //return NotFound();
       //}
       return View();
    }

    // POST: Personas/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Supervisor, SuperUser")]
    public async Task<IActionResult> DeleteConfirmed(int id) {
      if(User.Identity.IsAuthenticated){
        if(id != null && id > 0){
          try{
            var persona = await _context.Persona.FindAsync(id);
            persona.Estatus = false;
            persona.Email = " ";
            _context.Update(persona);
            await _context.SaveChangesAsync();
            LoggedUser = this.User.Identity.Name;
            _bRepo.Insert(new Bitacora() { UserId = LoggedUser, EventDate = DateTime.Now, Event = "Delete", Section = "Persona", Description = "Persona no. " + persona.Id + " eliminada." });
            return Json(new{success=true});
          }catch(Exception e){
            return Json(new{success=false, data=e});
          }
        }
        return NotFound();
      }
      return View();
    }

    private bool PersonaExists(int id) {
      return _context.Persona.Any(e => e.Id == id);
    }
  }
}

siges/Views/Personas/PersonsDeleted.cshtml
@model IEnumerable<siges.Models.Persona>

@{
    ViewData["Title"] = "Personas Eliminadas";
    List<siges.Models.Persona> personas = ViewData["persona"] as List<siges.Models.Persona>;
}

<div class="container">
    <div class="row">
        <div class="col">
            <h2>Personas Eliminadas</h2>
        </div>
            <div class="col align-self-center text-right">
                <a class="btn bg-blue marg-Float float" href='@Url.Action("Index", "Personas")' data-toggle="tooltip" data-placement="bottom" title="Regresar" data-original-title="Tooltip on bottom"><i class="fas fa-arrow-left"></i></a>
            </div>
    </div>
    <div class="row">
        <div class="col margBott4em">
                <table id="tableIndexClientes" data-toggle="table" data-search="true" data-show-columns="false" data-pagination="true" data-locale="es-MX" data-classes="table table-hover" data-page-size="5"  data-page-list="[5,10,25]" data-show-footer="true" data-sort-name="name">
                <thead>
                    <tr>
                        <th data-visible="false" data-field="id"></th>
                        <th>Fotografía</th>
                        <th data-sortable="true" data-field="name">@Html.DisplayNameFor(model => model.Nombre)</th>
                        <th data-sortable="true">Correo Electrónico</th>
                        <th data-sortable="true">@Html.DisplayNameFor(model => model.RFC)</th>
                        <th data-sortable="true">@Html.DisplayNameFor(model => model.Puesto)</th>
                        <th class="mobileHidden">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in personas) {
                        var nombre = item.Nombre +" "+ item.Paterno + " " + item.Materno;
                        var imgSrc = Url.Content("~/img/staff_ad.png");
                        if(item.Fotografia != null){
                        var base64 = Convert.ToBase64String(item.Fotografia);
                        imgSrc = String.Format("data:image/jpeg;base64,{0}",base64);
                        }
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Id)</td>
                            @* <td><img src="~/img/staff_ad.png" alt="Alternate Text" width="50" height="50" /></td> *@
                            <td><img src="@imgSrc" class="text-hide rounded" width="50" height="50" alt="@nombre"></td>
                            <td>@Html.DisplayFor(modelItem => nombre)</td>
                            <td>@Html.DisplayFor(modelItem => item.Email)</td>
                            <td>@Html.DisplayFor(modelItem => item.RFC)</td>
                            <td>@Html.DisplayFor(modelItem => item.Puesto)</td>
                            <td class="mobileHidden">
                                <a class="btn btn-success float_Table" data-toggle="tooltip" data-placement="bottom" title="Restaurar" data-original-title="Tooltip on bottom"><i class="fas fa-user-check"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section scripts{
<script>
    $('#tableIndexClientes').on('click-row.bs.table', (row, element, field) => {
        Swal.fire({
            icon: 'question',
            title: `${element.name} se restaurará`,
            text: `¿Seguro que deseas restaurarla?`,
            reverseButtons: true,
            showCancelButton: true,
            confirmButtonText:"Si, Restaurar",
            cancelButtonText:"No, Cancelar",
            confirmButtonColor:"#67E7CF",
            allowOutsideClick: false,
            allowEscapeKey: false,
            showCloseButton: true,
            closeButtonHtml: '<i class="fas fa-times"></i>'
        }).then(result => {
            if(result.value){
                $.ajax({
                    url: '@Url.Action("UpdateDP","Personas")',
                    method: "POST",
                    data: {
                        pid: element.id
                    },
                    async: true,
                    dataType: "json",
                    success: function (res){
                        if(res.success){
                            Swal.fire({
                                icon: 'success',
                                title: '¡Éxito!',
                                confirmButtonColor: "#67E7CF",
                                confirmButtonText:"Aceptar",
                                text: `La persona ${element.name} se restauró`,
                                onClose: ()=>{
                                    location.reload(true);
                                }
                            }).then(result => {
                                if (result.value) {
                                    location.reload(true);
                                }
                            });
                        }
                    }
                });
            }
            else{
                Swal.close();
            }
        });
    });
</script>
}